### ISSUE TITLE
Unable to Import PDFs - Invalid API Call

### ISSUE THREAD

**Issue by avagdumortesin** [deidril/pf2-pdf-en-import#46]
Attempting to import the PDF of Society Scenario 4-06 *Signal from the Electric Laboratory* fails to progress. I'm not sure if it's specific to me using Forge as my host or not, but when I attempt to import the PDF, the following appears in the console:
```
game:1  Uncaught (in promise) 
_0x1c188d {message: 'The API version "2.5.207" does not match the Worke….16.105".\n[Detected 1 package: pf2-pdf-en-import]', name: '_0x1c188d', details: '[object Object]', libwrapper_skip_package_detection: true, stack: 'Error\n    at _0x5b2881 (https://assets.forge-vtt.c…2-pdf-en-import/2.39/src/helyx.bundle.js:1:880690'}
details
: 
"[object Object]"
libwrapper_skip_package_detection
: 
true
message
: 
"The API version \"2.5.207\" does not match the Worker version \"2.16.105\".\n[Detected 1 package: pf2-pdf-en-import]"
name
: 
"_0x1c188d"
stack
: 
"Error\n    at _0x5b2881 (https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:915476)\n    at Object.<anonymous> (https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:915538)\n    at _0x594027 (https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:881129)\n    at Object.<anonymous> (https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:889622)\n    at _0x594027 (https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:881129)\n    at Object.<anonymous> (https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:887865)\n    at _0x594027 (https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:881129)\n    at https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:882995\n    at https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:883044\n    at _0x465639 (https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:880802)\n    at https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:880815\n    at createCommonjsModule (https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:880596)\n    at https://assets.forge-vtt.com/bazaar/modules/pf2-pdf-en-import/2.39/src/helyx.bundle.js:1:880690"
[[Prototype]]
: 
Error
```

I have tried multiple times to import without success. I was able to import Scenario 4-02 *Return to the Grave* earlier, but cannot import 4-06in a different world.

I just installed the module today, and I have the following versions:
FoundryVTT v11 306
PF2E System 5.2.3
libwrapper 1.12.13.0 (although I'm not seeing this as a dependency in `module.json`, so I'm wondering if it's not the `libwrapper` module for Foundry, but a different `libwrapper`.)
PF2 PDF Import 2.39

**Comment by avagdumortesin** [comment]
I'm an idiot and had PDF to Foundry installed and active as well. Closing.
